approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
author_approval: ignored
reviewers:
  - name: manager
    teams:
    - manager
    required: 1
    conditions:
      branches:
      - master
  - name: developer
    teams:
    - developer
    required: 1
    conditions:
      branches:
      - development
