version: 2
executorType: docker
containerInfo:
  - image: maven:3.5-jdk-8
stages:
  build:
    workDir: ~/BedwarsRel
    steps:
      - type: checkout
        
      - type: shell
        shell: /bin/bash --login
        command: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar && java -jar BuildTools.jar --rev 1.8 && java -jar BuildTools.jar --rev 1.8.3 && java -jar BuildTools.jar --rev 1.8.8 && java -jar BuildTools.jar --rev 1.9.2 && java -jar BuildTools.jar --rev 1.9.4 && java -jar BuildTools.jar --rev 1.10 && java -jar BuildTools.jar --rev 1.11 && java -jar BuildTools.jar --rev 1.12
          export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
          if [ "${CIRCLE_BRANCH}" == "master" ]
          then
            mvn clean install -P ci-release,attach-javadocs,attach-sources
          else
            mvn clean install -P ci-snapshot,attach-javadocs,attach-sources
          fi
          mkdir target/artifacts/
          cp target/BedwarsRel-*.jar target/artifacts/.
        
      - type: deploy
        shell: /bin/bash --login
        command: |
          export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
          if [ "${CIRCLE_BRANCH}" == "master" ]
          then
            mvn deploy -P ci-release,deploy-release,attach-javadocs,attach-sources --settings settings.xml
          elif [ "${CIRCLE_BRANCH}" == "develop" ]
          then
            mvn deploy -P ci-snapshot,deploy-snapshot,attach-javadocs,attach-sources --settings settings.xml
          fi

      - type: artifacts-store
        path: target/artifacts
        destination: artifacts
        
      - type: artifacts-store
        path: target/apidocs
        destination: apidocs

