version: 2
executorType: docker
containerInfo:
  - image: maven:3.5-jdk-8
stages:
  build:
    working_directory: ~/BedwarsRel
    steps:
      - type: checkout
      - run:
          name: "Getting Dependencies"
          command: 'cd build && ./get-dependencies.sh'
      - run:
          name: "Building BedwarsRel"
          command: |
            export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              mvn clean install -fae -P ci-release,attach-javadocs,attach-sources
            else
              mvn clean install -fae -P ci-snapshot,attach-javadocs,attach-sources
            fi
            mkdir -p plugin/target/artifacts/
            cp plugin/target/BedwarsRel-*.jar plugin/target/artifacts/.
      - run:
          name: "Deploying BedwarsRel"
          command: |
            export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              mvn deploy -P ci-release,deploy-release,attach-javadocs,attach-sources --settings settings.xml
            elif [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              mvn deploy -P ci-snapshot,deploy-snapshot,attach-javadocs,attach-sources --settings settings.xml
            fi
      - type: artifacts-store
        path: plugin/target/artifacts
        destination: artifacts

      - type: artifacts-store
        path: plugin/target/apidocs
        destination: apidocs

