version: 2
executorType: docker
containerInfo:
  - image: maven:3.5-jdk-8
stages:
  build:
    working_directory: ~/BedwarsRel
    steps:
      - run:
          name: "Downloading BuildTools.jar"
          command: 'mkdir BuildTools && cd BuildTools && wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar'
      - run:
          name: "Downloading CraftBukkit 1.8"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.8-R0.1-SNAPSHOT-latest.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.8-R0.1-SNAPSHOT-latest.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.8-R0.1-SNAPSHOT -Dpackaging=jar
      - run:
          name: "Building CraftBukkit 1.8.3"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.8.3-R0.1-SNAPSHOT-latest.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.8.3-R0.1-SNAPSHOT-latest.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.8.3-R0.1-SNAPSHOT -Dpackaging=jar
      - run:
          name: "Downloading CraftBukkit 1.8.8"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.8.8-R0.1-SNAPSHOT -Dpackaging=jar
      - run:
          name: "Downloading CraftBukkit 1.9.2"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.9.2-R0.1-SNAPSHOT -Dpackaging=jar
      - run:
          name: "Downloading CraftBukkit 1.9.4"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.9.4-R0.1-SNAPSHOT-latest.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.9.4-R0.1-SNAPSHOT-latest.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.9.4-R0.1-SNAPSHOT -Dpackaging=jar
      - run:
          name: "Downloading CraftBukkit 1.10.2"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.10.2-R0.1-SNAPSHOT -Dpackaging=jar
      - run:
          name: "Downloading CraftBukkit 1.11.2"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.11.2.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.11.2.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.11.2-R0.1-SNAPSHOT -Dpackaging=jar
      - run:
          name: "Building CraftBukkit 1.12"
          command: |
            cd CraftBukkit && wget https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.12.jar && \
            mvn install:install-file -Dfile=craftbukkit-1.12.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.12-R0.1-SNAPSHOT -Dpackaging=jar
      - type: checkout
      - run:
          name: "Building BedwarsRel"
          command: |
            export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              mvn clean install -fae -P ci-release,attach-javadocs,attach-sources
            else
              mvn clean install -fae -P ci-snapshot,attach-javadocs,attach-sources
            fi
            mkdir target/artifacts/
            cp target/BedwarsRel-*.jar target/artifacts/.
      - run:
          name: "Deploying BedwarsRel"
          command: |
            export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              mvn deploy -P ci-release,deploy-release,attach-javadocs,attach-sources --settings settings.xml
            elif [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              mvn deploy -P ci-snapshot,deploy-snapshot,attach-javadocs,attach-sources --settings settings.xml
            fi
      - type: artifacts-store
        path: target/artifacts
        destination: artifacts

      - type: artifacts-store
        path: target/apidocs
        destination: apidocs

