version: 2
executorType: docker
containerInfo:
  - image: maven:3.5-jdk-8
stages:
  build:
    working_directory: ~/BedwarsRel
    steps:
      - type: checkout
      - run:
          name: "Downloading BuildTools.jar"
          command: 'cd BuildTools && wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar'
      - run:
          name: "Building CraftBukkit 1.8"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.8'
      - run:
          name: "Building CraftBukkit 1.8.3"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.8.3'
      - run:
          name: "Building CraftBukkit 1.8.8"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.8.8'
      - run:
          name: "Building CraftBukkit 1.9.2"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.9'
      - run:
          name: "Building CraftBukkit 1.9.4"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.9.4'
      - run:
          name: "Building CraftBukkit 1.10.2"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.10.2'
      - run:
          name: "Building CraftBukkit 1.11.2"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.11.2'
      - run:
          name: "Building CraftBukkit 1.12"
          command: 'cd BuildTools && java -jar BuildTools.jar --rev 1.12'
      - run:
          name: "Building BedwarsRel"
          command: |
            export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              mvn clean install -P ci-release,attach-javadocs,attach-sources
            else
              mvn clean install -P ci-snapshot,attach-javadocs,attach-sources
            fi
            mkdir target/artifacts/
            cp target/BedwarsRel-*.jar target/artifacts/.
      - run:
          name: "Deploying BedwarsRel"
          command: |
            export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              mvn deploy -P ci-release,deploy-release,attach-javadocs,attach-sources --settings settings.xml
            elif [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              mvn deploy -P ci-snapshot,deploy-snapshot,attach-javadocs,attach-sources --settings settings.xml
            fi
      - type: artifacts-store
        path: target/artifacts
        destination: artifacts

      - type: artifacts-store
        path: target/apidocs
        destination: apidocs

